# Generated by Django 4.1.7 on 2023-03-01 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazy_danych', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('author', models.CharField(max_length=64)),
                ('content', models.TextField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('status', models.IntegerField(choices=[(1, 'w trakcie pisania'), (2, 'czeka na akceptacje'), (3, 'opublikowany')])),
                ('start_date', models.DateField(null=True)),
                ('end_date', models.DateField(null=True)),
            ],
        ),
    ]
