# Generated by Django 4.1.7 on 2023-03-01 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazy_danych', '0004_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='issue',
            field=models.IntegerField(),
        ),
    ]
