# Generated by Django 4.1.7 on 2023-03-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bazy_danych', '0008_song_album'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='article',
            field=models.ManyToManyField(to='bazy_danych.article'),
        ),
    ]
